### ISSUE TITLE
请问train.sh中的trainval.txt以及text.txt具体是怎样格式的呢？

### ISSUE THREAD

**Issue by yanzi6969** [imistyrain/yolo-face#3]
train  = /home/yanhe/data/widerface/trainval.txt
valid  = /home/yanhe/data/widerface/test.txt
能否把这两个文件共享下呢？

**Comment by imistyrain** [comment]
博文链接里有提到怎么生成这两个文件以及生成好的文件下载链接。
里面存放的是用来训练和测试图片的路径，每行一个路径。
images/0--Parade_0_Parade_marchingband_1_849.jpg
...
