### ISSUE TITLE
自己重新训练了yolo-face,检测不到任何人脸。

### ISSUE THREAD

**Issue by yanzi6969** [imistyrain/yolo-face#4]
你好，我使用celeba库，20万作为训练，2万多作为测试，参数按照您设置的，没有改动，使用的yoloface.cfg,在darknet19_448.conv.23基础上训练的。问题出在哪里呢？

**Comment by joeysu** [comment]
@yanzi6969 loss下降了吗？

**Comment by imistyrain** [comment]
可能是训练次数不够导致的
